services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Koddistortion\BodyBook\PlatformBundle\:
        resource: '../*'
        exclude: '../{Entity,Repository}'

    Koddistortion\BodyBook\PlatformBundle\Service\OAuth\Nokia\NokiaClientFactory:
      arguments: ['@hwi_oauth.storage.session', '@doctrine.orm.entity_manager', '@logger', '@hwi_oauth.http_client', '@security.http_utils']

    Koddistortion\BodyBook\PlatformBundle\Service\OAuth\Nokia\NokiaClient:
      public: true
      factory: 'Koddistortion\BodyBook\PlatformBundle\Service\OAuth\Nokia\NokiaClientFactory:createClient'
      arguments: ['@security.token_storage']

    koddistortion.bodybook.oauth_aware.user_provider:
      class: Koddistortion\BodyBook\PlatformBundle\Service\OAuthUserProvider
      arguments:
        - '@fos_user.user_manager'
        - '@fos_user.util.token_generator.default'
        - { google: google_id, facebook: facebook_id, twitter: twitter_id }

    Koddistortion\BodyBook\PlatformBundle\Form\Extension\ButtonIconTypeExtension:
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }

    twig.extension.text:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
